name: Build and TEST

on:
  push:
    branches: [main]
    paths:
      - 'web/**'

  pull_request:
    branches: [main]
    paths:
      - 'web/**'

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "pnpm"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Format check
        run: pnpm prettier --check "src/**/*.{js,jsx,ts,tsx,json,css,md}"

      - name: Build
        run: pnpm build

      - name: Run Jest tests
        run: pnpm test

      - name: Run E2E tests
        run: pnpm test:e2e:ci

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
